//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using Unity.Entities;
using Unity.NetCode;
using Unity.NetCode.EditorTests.Generated;

namespace Unity.NetCode.EditorTests.Generated
{
    [UpdateInGroup(typeof(ClientAndServerInitializationSystemGroup))]
    public class GhostComponentSerializerRegistrationSystem : SystemBase
    {
        protected override void OnCreate()
        {
            var ghostCollectionSystem = World.GetOrCreateSystem<GhostCollectionSystem>();
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsTestInputGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsTestExtrapolatedGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsGhostGenTestTypeFlatGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsGhostGenTestTypes_GhostGenBigStructGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsGhostValueSerializerGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsGhostGenTest_BufferGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsGhostGen_InterpolatedStructGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsGhostGen_IntStructGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsGhostGen_BufferInterpolatedGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsGhostGenBuffer_BufferCompositeGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsGhostGenBuffer_ByteBufferGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsDynamicBufferSerializationTests_GhostServerOnlyBufferGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsDynamicBufferSerializationTests_GhostClientOnlyBufferGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsDynamicBufferSerializationTests_GhostPredictedOnlyBufferGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsDynamicBufferSerializationTests_GhostInterpolatedOnlyBufferGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsGhostTypeIndexGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsChildLevelComponentGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsGhostPredictedOnlyGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsGhostInterpolatedOnlyGhostComponentSerializer.State);
            ghostCollectionSystem.AddSerializer(UnityNetCodeTestsPerPrefabOverridesTests_TranslationVariantTestGhostComponentSerializer.State);
        }

        protected override void OnUpdate()
        {
            var parentGroup = World.GetExistingSystem<InitializationSystemGroup>();
            if (parentGroup != null)
            {
                parentGroup.RemoveSystemFromUpdateList(this);
            }
        }
    }
}